apiVersion: apps/v1
kind: Deployment
metadata:
  name: adonis-kub-projeto
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adonis-kub-projeto
  template:
    metadata:
      labels:
        app: adonis-kub-projeto
    spec:
      containers:
        - name: adonis-kub-projeto
          image: joaoof/adonis-kub-projeto:latest
          env:
            - name: PORT
              value: "3333"
            - name: HOST
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "development"
            - name: APP_KEY
              value: "WryRbf4T2p7FvwxiPHgJVsQ8JEHZX-Vs"
            - name: DRIVE_DISK
              value: "local"
            - name: CACHE_VIEWS
              value: "false"
            - name: SMTP_HOST
              value: "sandbox.smtp.mailtrap.io"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USERNAME
              value: "4cd40d834b414c"
            - name: SMTP_PASSWORD
              value: "a96f084db232e7"
            - name: DB_CONNECTION
              value: "pg"
            - name: PG_HOST
              value: "0.0.0.0"
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: "bhayron"
            - name: PG_PASSWORD
              value: "secret123"
            - name: PG_DB_NAME
              value: "sistema"
